### ISSUE TITLE
Tests(watcher): debug tokyo runtime 

### ISSUE THREAD

**Issue by SHAcollision** [pubky/pubky-nexus#206]
We are facing this error often and randomly watcher tests
```
Error while handling event: unexpected response for PULL: Err(IOError { detail: Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown." } })
```
Possibly due to the way we use the homeserver concurrently or pubky_client (most likely the client and how we pass it down the event processors!), but who knows. It limis the reproducibility of out tests.

Also, killing the tests `Ctrl+C` does not fully stop the tests. Might be related.

**Comment by amirRamirfatahi** [comment]
After digging into this for some time, and trying out multiple culprits, it turns out that this error is happening in our watcher tests because when you run `cargo test`  and there are multiple tests to be run, each and everyone of them starts its own Tokio runtime and this sometimes creates the issue's error because of our database connectors which are defined like this:
`pub static NEO4J_CONNECTOR: OnceCell<Neo4jConnector> = OnceCell::new();` and these runtimes all share this connector and this is the reason for the conflict.  
After looking for solutions, this [crate](https://docs.rs/crate/tokio-shared-rt/latest) seems to be what we're looking for, as it causes all the tests to share the same Tokio runtime. 
Another option would be to run all the tests using only 1 thread by adding `--test-threads=1`, which is not favorable.
